version: '3'
services:
  jupyterlab:
    build:
      context: ./python
      dockerfile: DockerFile
    env_file:
      - .env
    working_dir: /work
    volumes:
      - ./work:/work
    ports:
      - "8501:8501"
      - "8888:8888"
    command: jupyter-lab --ip 0.0.0.0 --allow-root -b localhost